### ISSUE TITLE
[Approach not finalised] Improve AV scanner performance

### ISSUE THREAD

**Issue by BadalZ** [topcoder-platform/av-scanner-service#8]
Badal: I just tried (only) scanning a file using https://api.topcoder-dev.com/v5/scan with filesize 135M. It took me 8 minutes for scanning result. 

CWD: we may need to develop a sorta of batch process for this with a worker app in the scanning service so that the scanner API receives a request to scan a file w/ a URL and the worker app goes and fetches that URL

This approach is in discussion phase.

**Comment by BadalZ** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [AV scanner performance improvement](https://trello.com/c/Ce36v6w9/38-av-scanner-performance-improvement)

**Comment by callmekatootie** [comment]
Right now, we:

- Take the file passed to us and check if the file is in DMZ area. If not, we bring it to DMZ area
- We then scan the file, and use the result to either move the file to Quarantine area of Clean area.

Since scanning can take time, what we could do is:
- have processor send the file to av scanner and stop right there. Additionally, processor can send an endpoint where clamav can send the results to (think webhooks)
- If I understand [this SO post](https://askubuntu.com/questions/606488/how-to-scan-more-than-one-location-at-the-same-time-with-clamav) clearly, then clamav is capable of scanning in parallel, so I guess we can utilize that and send multiple requests to clamav (?)
- Once scan is complete, clamav calls the webhook and passes the results to it.
- processor basically picks up from where it left off at point 1.

Thoughts?

cc @cwdcwd

**Comment by cwdcwd** [comment]
here's what I'm thinking
- we keep the `/scan` for smaller/quick scans
- we create a new endpoint in the API called `/batchScan` (or something like that)
- `/batchScan` POST takes a payload with
  * URL of file to scan
  * submissionId
- 
- the `/batchScan` endpoint:
  * adds a "status" field to the payload of "unscanned"
  *  publishes a message to the event bus with the payload to a topic like `avscan.action.scan` 
  * 
- a new processor listening on the `avscan.action.scan` channel: 
  * picks up the event
  * scans the file 
  * updates the payload status field to "scanned"
  * adds scan results to payload 
  * publishes payload to `avscan.action.scan`  
- the originating processor monitors `avscan.action.scan` for events
  * picks up events and checks for the  "scanned" status. ignores all others
  * runs through regular review posting process with scanned results based on the submissionId

This flow adds a new processor and a new endpoint as well as expands the existing base processor slightly. It may seem a little bit roundabout to do this but what this architecture gives us is 
- a new batch processing endpoint that any service can utilize
- a common way to receive scan results on the bus
- allows us to defer large files off to a separate, asychronous process

**Comment by cwdcwd** [comment]
@callmekatootie @BadalZ any thoughts?

**Comment by BadalZ** [comment]
This approach looks good to me and I have asked @callmekatootie to start working on this.

**Comment by callmekatootie** [comment]
Approach looks fine to me. I will proceed to create a specification and launch contest shortly

**Comment by callmekatootie** [comment]
@cwdcwd Questions:
1. When you say the new processor will scan the file, will it call the `/scan` endpoint of the `av-scanner-service` itself, or will the processor have its own scanner (which will be a replica of the code called when working with the `/scan` endpoint?
2. How would this be different from the existing processor (the one that will call `/batchScan`) instead posting an event to the bus itself about the scan, instead of calling `av-scanner-service` to do that task?

**Comment by callmekatootie** [comment]
Another question:
(3) Does the submission processor check for the file size before deciding if it needs to call `/scan` or `/batchScan`? Or will it always call the latter irrespective of the size?
(4) Do we need to add any checks on the size for `/scan` or `/batchScan` - you know, like if the file size is less / more than foobar, then we scan the file else we delegate it to the other endpoint?

**Comment by cwdcwd** [comment]
1. I was thinking that the processor could connect directly to the clam AV instance and feed it the file. If that's not possible then I suppose the clam AV instance would have to be present in the same docker image as the processor
2. I want to be able to initiate scans both via an API call or via event bus but it all comes down to event bus. the point of `/batchScan` is so that an API client can check back later to see the results on a GET call if need be

**Comment by cwdcwd** [comment]
3. probably a good idea to check or we could just make is simple and make all calls `/batchScan` calls
4. that would be a very elegant way to do it but see previous bullet

**Comment by callmekatootie** [comment]
@BadalZ @cwdcwd 

Changes have been carried out.

Three Pull Requests across repositories need to be merged in for this improvement:

1. https://github.com/topcoder-platform/submission-scanner-processor/pull/1
2. https://github.com/topcoder-platform/submission-processor/pull/25
3. https://github.com/topcoder-platform/av-scanner-service/pull/10

**Comment by BadalZ** [comment]
All 3 PR merged.
